/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor;

/**
 *
 * @author ml
 */
public class HlavniOkno extends javax.swing.JFrame {

    /**
     * Creates new form HlavniOkno
     */
    public HlavniOkno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupCodePages = new javax.swing.ButtonGroup();
        toolBar = new javax.swing.JToolBar();
        toolNew = new javax.swing.JButton();
        toolOpen = new javax.swing.JButton();
        toolSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JEditorPane();
        statusBar = new javax.swing.JPanel();
        infoLeft = new javax.swing.JLabel();
        infoCenter = new javax.swing.JLabel();
        infoRight = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemNew = new javax.swing.JMenuItem();
        itemOpen = new javax.swing.JMenuItem();
        itemSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemInfo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemClose = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        itemCut = new javax.swing.JMenuItem();
        itemCopy = new javax.swing.JMenuItem();
        itemPaste = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemFind = new javax.swing.JMenuItem();
        itemRaplace = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemSelectAll = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        menuView = new javax.swing.JMenu();
        itemToolBar = new javax.swing.JCheckBoxMenuItem();
        itemStatusBar = new javax.swing.JCheckBoxMenuItem();
        itemColor = new javax.swing.JMenuItem();
        itemFont = new javax.swing.JMenuItem();
        menuCodePage = new javax.swing.JMenu();
        itemUTF8 = new javax.swing.JRadioButtonMenuItem();
        itemWin1250 = new javax.swing.JRadioButtonMenuItem();
        itemISO = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editorek");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setName("frame"); // NOI18N
        getContentPane().setLayout(new java.awt.BorderLayout(0, 1));

        toolBar.setRollover(true);

        toolNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/new.png"))); // NOI18N
        toolNew.setText("Nový");
        toolNew.setFocusable(false);
        toolNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolNew);

        toolOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/open.png"))); // NOI18N
        toolOpen.setMnemonic('o');
        toolOpen.setText("Otevřít");
        toolOpen.setToolTipText("Otevře textový dokument");
        toolOpen.setFocusable(false);
        toolOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolOpen);

        toolSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/save.png"))); // NOI18N
        toolSave.setMnemonic('u');
        toolSave.setText("Uložit");
        toolSave.setToolTipText("Uloží textový dokument");
        toolSave.setFocusable(false);
        toolSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolSave);

        getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);

        editor.setPreferredSize(new java.awt.Dimension(106, 400));
        jScrollPane1.setViewportView(editor);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        statusBar.setBackground(new java.awt.Color(204, 204, 204));
        statusBar.setPreferredSize(new java.awt.Dimension(610, 30));
        statusBar.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        infoLeft.setBackground(new java.awt.Color(0, 102, 255));
        infoLeft.setForeground(new java.awt.Color(255, 255, 255));
        infoLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLeft.setText("Název souboru");
        infoLeft.setOpaque(true);
        statusBar.add(infoLeft);

        infoCenter.setBackground(new java.awt.Color(255, 204, 0));
        infoCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoCenter.setText("Vlastnosti souboru");
        infoCenter.setOpaque(true);
        statusBar.add(infoCenter);

        infoRight.setBackground(new java.awt.Color(102, 153, 0));
        infoRight.setForeground(new java.awt.Color(255, 255, 255));
        infoRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoRight.setText("Parametry textu");
        infoRight.setOpaque(true);
        statusBar.add(infoRight);

        getContentPane().add(statusBar, java.awt.BorderLayout.PAGE_END);

        menuFile.setMnemonic('s');
        menuFile.setText("Soubor");
        menuFile.setToolTipText("");

        itemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        itemNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/new-small.png"))); // NOI18N
        itemNew.setMnemonic('n');
        itemNew.setText("Nový");
        menuFile.add(itemNew);

        itemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/open-small.png"))); // NOI18N
        itemOpen.setMnemonic('o');
        itemOpen.setText("Otevřít...");
        menuFile.add(itemOpen);

        itemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/save-small.png"))); // NOI18N
        itemSave.setMnemonic('u');
        itemSave.setText("Uložit...");
        menuFile.add(itemSave);
        menuFile.add(jSeparator1);

        itemInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        itemInfo.setMnemonic('i');
        itemInfo.setText("Informace o souboru");
        menuFile.add(itemInfo);
        menuFile.add(jSeparator2);

        itemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itemClose.setMnemonic('k');
        itemClose.setText("Konec");
        menuFile.add(itemClose);

        menuBar.add(menuFile);

        menuEdit.setMnemonic('p');
        menuEdit.setText("Úpravy");

        itemCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        itemCut.setMnemonic('v');
        itemCut.setText("Vyjmout");
        menuEdit.add(itemCut);

        itemCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemCopy.setMnemonic('k');
        itemCopy.setText("Kopírovat");
        menuEdit.add(itemCopy);

        itemPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        itemPaste.setMnemonic('l');
        itemPaste.setText("Vložit");
        menuEdit.add(itemPaste);
        menuEdit.add(jSeparator3);

        itemFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemFind.setMnemonic('h');
        itemFind.setText("Hledat...");
        menuEdit.add(itemFind);

        itemRaplace.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        itemRaplace.setMnemonic('n');
        itemRaplace.setText("Nahradit...");
        menuEdit.add(itemRaplace);
        menuEdit.add(jSeparator4);

        itemSelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemSelectAll.setMnemonic('b');
        itemSelectAll.setText("Vybrat vše");
        menuEdit.add(itemSelectAll);

        menuBar.add(menuEdit);

        menuSettings.setMnemonic('n');
        menuSettings.setText("Nastavení");

        menuView.setMnemonic('z');
        menuView.setText("Zobrazení");

        itemToolBar.setSelected(true);
        itemToolBar.setText("Panel nástrojů");
        menuView.add(itemToolBar);

        itemStatusBar.setSelected(true);
        itemStatusBar.setText("Stavový řádek");
        menuView.add(itemStatusBar);

        menuSettings.add(menuView);

        itemColor.setMnemonic('b');
        itemColor.setText("Barva pozadí...");
        menuSettings.add(itemColor);

        itemFont.setMnemonic('p');
        itemFont.setText("Písmo...");
        menuSettings.add(itemFont);

        menuCodePage.setMnemonic('k');
        menuCodePage.setText("Kódování znaků");
        menuCodePage.setToolTipText("");

        groupCodePages.add(itemUTF8);
        itemUTF8.setSelected(true);
        itemUTF8.setText("UTF-8");
        menuCodePage.add(itemUTF8);

        groupCodePages.add(itemWin1250);
        itemWin1250.setText("Windows 1250");
        menuCodePage.add(itemWin1250);

        groupCodePages.add(itemISO);
        itemISO.setText("ISO-8859-2");
        menuCodePage.add(itemISO);

        menuSettings.add(menuCodePage);

        menuBar.add(menuSettings);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavniOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editor;
    private javax.swing.ButtonGroup groupCodePages;
    private javax.swing.JLabel infoCenter;
    private javax.swing.JLabel infoLeft;
    private javax.swing.JLabel infoRight;
    private javax.swing.JMenuItem itemClose;
    private javax.swing.JMenuItem itemColor;
    private javax.swing.JMenuItem itemCopy;
    private javax.swing.JMenuItem itemCut;
    private javax.swing.JMenuItem itemFind;
    private javax.swing.JMenuItem itemFont;
    private javax.swing.JRadioButtonMenuItem itemISO;
    private javax.swing.JMenuItem itemInfo;
    private javax.swing.JMenuItem itemNew;
    private javax.swing.JMenuItem itemOpen;
    private javax.swing.JMenuItem itemPaste;
    private javax.swing.JMenuItem itemRaplace;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JMenuItem itemSelectAll;
    private javax.swing.JCheckBoxMenuItem itemStatusBar;
    private javax.swing.JCheckBoxMenuItem itemToolBar;
    private javax.swing.JRadioButtonMenuItem itemUTF8;
    private javax.swing.JRadioButtonMenuItem itemWin1250;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCodePage;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenu menuView;
    private javax.swing.JPanel statusBar;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JButton toolNew;
    private javax.swing.JButton toolOpen;
    private javax.swing.JButton toolSave;
    // End of variables declaration//GEN-END:variables
}
